# Generated by Django 6.0 on 2025-12-04 22:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash amount received from customer (for Cash payments)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Change given to customer (for Cash payments)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
